### Compose-File f체r unsere Microservice-Architektur
### Dieses Beispiel zeigt nur den frontend-Dienst
### Die weitere Dienste werden sp채ter dazukonfiguriert.

# Definition der einzelnen Services / Containers:
services:
  # wir definieren den frontend-Service:
  frontend:
    # das Docker-Image soll ab dem lokalen Folder frontend/ gebuildet werden:
    # dort befindet sich das Dockerfile:
    build: frontend/
    # wir mappen den Host-Port 8020 auf den Container-Port 3000:
    ports:
      - "8020:3000"
    # Wir h채ngen den frontend-Folder als Volume ein:
    volumes:
      - ./frontend:/server
    # optional: falls CMD im Dockerfile nicht definiert ist,
    # definieren wir hier, was beim Start ausgef체hrt werden soll:
    # command: sh -c "npm install && npm run build && node server.js"
