@startuml microservice_arch
title Ziel-Architektur als Microservices

[Client - Browser] as client
node "Microservices" {
	package "statische Seiten-Service" as static_site {
		[API-Proxy] as proxy
		[gebildete Seiten] as build_site
		[Site-Builder] as site_builder
	}
	[Form-Service] as form_backend
	[Kommentar-Service] as comment_backend
	[Datenbank - Postgresql] as db
	[mkdocs-Dokumentation] as doc
}

[Email-Dienst (extern)] as email

client ..> static_site: Ruft auf
client ..> doc: Ruft auf
proxy ..> form_backend: Ruft auf
proxy ..> comment_backend: Ruft auf
form_backend ..> email: sendet
form_backend ..> db: speichert
comment_backend ..> db: speichert, liest
site_builder .up.> build_site: generiert
@enduml